name: Docker Image CI
on: push
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file src/shadowbox/docker/Dockerfile --build-arg NODE_IMAGE='node:16.18.0-alpine3.16' --build-arg VERSION='1.0' --tag one-outline-server:$(date +%s)
    - name: Build container
    - uses: docker/build-push-action@v5
      with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
